package cn.lcxqy.starfree.meta;

import cn.lcxqy.starfree.cache.LegacyProjectionCacheInvalidator;
import cn.lcxqy.starfree.content.ContentService;
import cn.lcxqy.starfree.security.LegacyTokenService;
import cn.lcxqy.starfree.security.StaffAccess;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.jdbc.core.JdbcTemplate;

import java.util.ArrayList;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

@ExtendWith(MockitoExtension.class)
class MetaAdministrationServiceTest {
    @Mock
    private ContentService contents;
    @Mock
    private LegacyTokenService tokens;
    @Mock
    private LegacyProjectionCacheInvalidator caches;

    private StubJdbcTemplate jdbc;
    private MetaService service;

    @BeforeEach
    void setUp() {
        jdbc = new StubJdbcTemplate();
        service = new MetaService(jdbc, new ObjectMapper(), contents,
                new StaffAccess(tokens), caches);
        when(tokens.userId("admin-token")).thenReturn(1L);
        when(tokens.userById(1L)).thenReturn(row(
                "uid", 1, "name", "root", "group", "administrator"));
    }

    @Test
    void addUsesAllowlistedFieldsAndInitializesRelationshipCountItself() {
        jdbc.updateResult = 1;

        int changed = service.add("admin-token", row(
                "name", "Java", "slug", "java", "type", "category",
                "description", "language", "orderKey", 9, "count", 999,
                "mid", 123, "unknown", "ignored"));

        assertThat(changed).isEqualTo(1);
        assertThat(jdbc.lastUpdateSql).contains("count,`order`").doesNotContain("unknown");
        assertThat(jdbc.lastUpdateArgs).containsExactly(
                "Java", "java", "category", "language", 9, 0, "", 0);
        verify(caches).afterMetaWrite();
        verify(caches).afterDashboardCountWrite();
    }

    @Test
    void editCannotChangeTypeOrDerivedCount() {
        jdbc.metas.put(7L, row(
                "mid", 7, "name", "Old", "slug", "old", "type", "category", "parent", 0));
        jdbc.updateResult = 1;

        int changed = service.edit("admin-token", row(
                "mid", 7, "name", "New", "type", "tag", "count", 500));

        assertThat(changed).isEqualTo(1);
        assertThat(jdbc.lastUpdateSql)
                .isEqualTo("UPDATE starfree_metas SET `name`=? WHERE mid=?");
        assertThat(jdbc.lastUpdateArgs).containsExactly("New", 7L);
        verify(caches).afterMetaWrite();
    }

    @Test
    void editRejectsAParentThatWouldCreateACycle() {
        jdbc.metas.put(7L, row(
                "mid", 7, "name", "Parent", "slug", "parent", "type", "category", "parent", 0));
        jdbc.metas.put(8L, row(
                "mid", 8, "name", "Child", "slug", "child", "type", "category", "parent", 7));

        assertThrows(IllegalArgumentException.class,
                () -> service.edit("admin-token", row("mid", 7, "parent", 8)));

        assertThat(jdbc.updateCalls).isZero();
        verify(caches, never()).afterMetaWrite();
    }

    @Test
    void deleteNormalizesMultiTableAffectedRowsToOne() {
        jdbc.metas.put(7L, row(
                "mid", 7, "name", "Java", "slug", "java", "type", "category", "parent", 0));
        jdbc.updateResult = 4;

        assertThat(service.delete("admin-token", 7)).isEqualTo(1);
        assertThat(jdbc.lastUpdateSql).contains("DELETE m,r").contains("starfree_relationships");
        verify(caches).afterMetaWrite();
    }

    @Test
    void recommendAcceptsOnlyBinaryState() {
        jdbc.metas.put(7L, row(
                "mid", 7, "name", "Java", "slug", "java", "type", "category", "parent", 0));

        assertThrows(IllegalArgumentException.class,
                () -> service.recommend("admin-token", 7, 2));

        assertThat(jdbc.updateCalls).isZero();
    }

    private Map<String, Object> row(Object... values) {
        Map<String, Object> row = new LinkedHashMap<>();
        for (int index = 0; index < values.length; index += 2) {
            row.put(String.valueOf(values[index]), values[index + 1]);
        }
        return row;
    }

    /** In-memory SQL boundary used to inspect the exact whitelist generated by MetaService. */
    private static final class StubJdbcTemplate extends JdbcTemplate {
        private final Map<Long, Map<String, Object>> metas = new LinkedHashMap<>();
        private int count;
        private int updateResult;
        private int updateCalls;
        private String lastUpdateSql;
        private List<Object> lastUpdateArgs = Collections.emptyList();

        @Override
        public List<Map<String, Object>> queryForList(String sql, Object... args) {
            if (sql.contains("FROM starfree_metas WHERE mid=?") && args.length > 0) {
                Map<String, Object> meta = metas.get(((Number) args[0]).longValue());
                return meta == null ? Collections.<Map<String, Object>>emptyList()
                        : Collections.singletonList(meta);
            }
            return Collections.emptyList();
        }

        @Override
        @SuppressWarnings("unchecked")
        public <T> T queryForObject(String sql, Class<T> requiredType, Object... args) {
            return (T) Integer.valueOf(count);
        }

        @Override
        public int update(String sql, Object... args) {
            updateCalls++;
            lastUpdateSql = sql;
            lastUpdateArgs = new ArrayList<>();
            Collections.addAll(lastUpdateArgs, args);
            return updateResult;
        }
    }
}
